import type { Course } from "./types";

export const courses: Course[] = [
  {
    id: "python-fundamentals",
    title: "Python Temelleri",
    description:
      "Sıfırdan Python programlama. Değişkenler, veri tipleri, kontrol akışı, fonksiyonlar ve nesne yönelimli programlama.",
    category: "Programlama",
    level: "Başlangıç",
    icon: "🐍",
    totalModules: 5,
    totalLessons: 24,
    estimatedHours: 12,
    progress: 68,
    enrolled: true,
    tags: ["Python", "Temel", "OOP"],
    instructor: "Orka AI",
    rating: 4.8,
    students: 2340,
    modules: [
      {
        id: "py-m1",
        title: "Giriş ve Kurulum",
        description: "Python'ı tanıyın, geliştirme ortamınızı kurun.",
        duration: "1.5 saat",
        lessons: [
          { id: "py-l1", title: "Python Nedir?", type: "article", duration: "10 dk", completed: true },
          { id: "py-l2", title: "Kurulum ve IDE Seçimi", type: "article", duration: "15 dk", completed: true },
          { id: "py-l3", title: "İlk Programınız", type: "exercise", duration: "20 dk", completed: true },
          { id: "py-l4", title: "Modül Sınavı", type: "quiz", duration: "10 dk", completed: true },
        ],
      },
      {
        id: "py-m2",
        title: "Değişkenler ve Veri Tipleri",
        description: "Temel veri tipleri, tip dönüşümleri ve string işlemleri.",
        duration: "2 saat",
        lessons: [
          { id: "py-l5", title: "Sayılar ve Stringler", type: "article", duration: "15 dk", completed: true },
          { id: "py-l6", title: "Listeler ve Tuple'lar", type: "article", duration: "20 dk", completed: true },
          { id: "py-l7", title: "Dictionary ve Set", type: "article", duration: "20 dk", completed: true },
          { id: "py-l8", title: "Tip Dönüşümleri", type: "exercise", duration: "25 dk", completed: true },
          { id: "py-l9", title: "Modül Sınavı", type: "quiz", duration: "10 dk", completed: true },
        ],
      },
      {
        id: "py-m3",
        title: "Kontrol Akışı",
        description: "if/else, döngüler, koşullu ifadeler ve hata yönetimi.",
        duration: "2.5 saat",
        lessons: [
          { id: "py-l10", title: "if/elif/else", type: "article", duration: "15 dk", completed: true },
          { id: "py-l11", title: "for ve while Döngüleri", type: "article", duration: "20 dk", completed: true },
          { id: "py-l12", title: "List Comprehension", type: "article", duration: "15 dk", completed: false },
          { id: "py-l13", title: "Hata Yönetimi (try/except)", type: "article", duration: "20 dk", completed: false },
          { id: "py-l14", title: "Pratik Alıştırmalar", type: "exercise", duration: "30 dk", completed: false },
        ],
      },
      {
        id: "py-m4",
        title: "Fonksiyonlar",
        description: "Fonksiyon tanımlama, parametreler, lambda ve dekoratörler.",
        duration: "3 saat",
        lessons: [
          { id: "py-l15", title: "Fonksiyon Temelleri", type: "article", duration: "15 dk", completed: false },
          { id: "py-l16", title: "Parametreler ve Dönüş Değerleri", type: "article", duration: "20 dk", completed: false },
          { id: "py-l17", title: "Lambda ve Map/Filter", type: "article", duration: "20 dk", completed: false },
          { id: "py-l18", title: "Dekoratörler", type: "video", duration: "25 dk", completed: false },
          { id: "py-l19", title: "Modül Sınavı", type: "quiz", duration: "15 dk", completed: false },
        ],
      },
      {
        id: "py-m5",
        title: "Nesne Yönelimli Programlama",
        description: "Sınıflar, kalıtım, polimorfizm ve soyut sınıflar.",
        duration: "3 saat",
        lessons: [
          { id: "py-l20", title: "Sınıf ve Nesne", type: "article", duration: "20 dk", completed: false },
          { id: "py-l21", title: "Kalıtım", type: "article", duration: "20 dk", completed: false },
          { id: "py-l22", title: "Polimorfizm", type: "article", duration: "15 dk", completed: false },
          { id: "py-l23", title: "OOP Projesi", type: "exercise", duration: "45 dk", completed: false },
          { id: "py-l24", title: "Final Sınavı", type: "quiz", duration: "20 dk", completed: false },
        ],
      },
    ],
  },
  {
    id: "machine-learning",
    title: "Makine Öğrenmesi",
    description:
      "Denetimli ve denetimsiz öğrenme, model değerlendirme, sinir ağları ve gerçek dünya uygulamaları.",
    category: "Yapay Zeka",
    level: "Orta",
    icon: "🧠",
    totalModules: 6,
    totalLessons: 30,
    estimatedHours: 20,
    progress: 35,
    enrolled: true,
    tags: ["ML", "Sinir Ağları", "Scikit-learn"],
    instructor: "Orka AI",
    rating: 4.9,
    students: 1850,
    modules: [
      {
        id: "ml-m1",
        title: "ML'e Giriş",
        description: "Makine öğrenmesi nedir, türleri ve uygulama alanları.",
        duration: "2 saat",
        lessons: [
          { id: "ml-l1", title: "ML Nedir?", type: "article", duration: "15 dk", completed: true },
          { id: "ml-l2", title: "Denetimli vs Denetimsiz", type: "article", duration: "20 dk", completed: true },
          { id: "ml-l3", title: "Veri Hazırlama", type: "exercise", duration: "30 dk", completed: true },
          { id: "ml-l4", title: "Modül Sınavı", type: "quiz", duration: "10 dk", completed: true },
        ],
      },
      {
        id: "ml-m2",
        title: "Denetimli Öğrenme",
        description: "Regresyon, sınıflandırma ve karar ağaçları.",
        duration: "3.5 saat",
        lessons: [
          { id: "ml-l5", title: "Lineer Regresyon", type: "article", duration: "20 dk", completed: true },
          { id: "ml-l6", title: "Lojistik Regresyon", type: "article", duration: "20 dk", completed: true },
          { id: "ml-l7", title: "Karar Ağaçları", type: "article", duration: "25 dk", completed: false },
          { id: "ml-l8", title: "Random Forest", type: "article", duration: "20 dk", completed: false },
          { id: "ml-l9", title: "Pratik Proje", type: "exercise", duration: "40 dk", completed: false },
        ],
      },
      {
        id: "ml-m3",
        title: "Denetimsiz Öğrenme",
        description: "Kümeleme, boyut indirgeme ve anomali tespiti.",
        duration: "3 saat",
        lessons: [
          { id: "ml-l10", title: "K-Means Kümeleme", type: "article", duration: "20 dk", completed: false },
          { id: "ml-l11", title: "PCA", type: "article", duration: "25 dk", completed: false },
          { id: "ml-l12", title: "Anomali Tespiti", type: "article", duration: "20 dk", completed: false },
          { id: "ml-l13", title: "Pratik Proje", type: "exercise", duration: "35 dk", completed: false },
          { id: "ml-l14", title: "Modül Sınavı", type: "quiz", duration: "15 dk", completed: false },
        ],
      },
      {
        id: "ml-m4",
        title: "Model Değerlendirme",
        description: "Metrikler, cross-validation ve hiperparametre optimizasyonu.",
        duration: "2.5 saat",
        lessons: [
          { id: "ml-l15", title: "Accuracy, Precision, Recall", type: "article", duration: "20 dk", completed: false },
          { id: "ml-l16", title: "Cross-Validation", type: "article", duration: "20 dk", completed: false },
          { id: "ml-l17", title: "Grid Search", type: "exercise", duration: "30 dk", completed: false },
          { id: "ml-l18", title: "Modül Sınavı", type: "quiz", duration: "15 dk", completed: false },
        ],
      },
      {
        id: "ml-m5",
        title: "Sinir Ağları",
        description: "Perceptron, backpropagation ve derin öğrenmeye giriş.",
        duration: "4 saat",
        lessons: [
          { id: "ml-l19", title: "Perceptron", type: "article", duration: "20 dk", completed: false },
          { id: "ml-l20", title: "Backpropagation", type: "article", duration: "25 dk", completed: false },
          { id: "ml-l21", title: "Aktivasyon Fonksiyonları", type: "article", duration: "20 dk", completed: false },
          { id: "ml-l22", title: "PyTorch ile İlk Model", type: "exercise", duration: "45 dk", completed: false },
          { id: "ml-l23", title: "Modül Sınavı", type: "quiz", duration: "15 dk", completed: false },
        ],
      },
      {
        id: "ml-m6",
        title: "Gerçek Dünya Projesi",
        description: "Uçtan uca bir ML projesi geliştirin.",
        duration: "5 saat",
        lessons: [
          { id: "ml-l24", title: "Problem Tanımlama", type: "article", duration: "15 dk", completed: false },
          { id: "ml-l25", title: "Veri Toplama ve Temizleme", type: "exercise", duration: "40 dk", completed: false },
          { id: "ml-l26", title: "Model Eğitimi", type: "exercise", duration: "45 dk", completed: false },
          { id: "ml-l27", title: "Model Deployment", type: "exercise", duration: "40 dk", completed: false },
          { id: "ml-l28", title: "Sunum ve Dokümantasyon", type: "article", duration: "30 dk", completed: false },
          { id: "ml-l29", title: "Peer Review", type: "exercise", duration: "30 dk", completed: false },
          { id: "ml-l30", title: "Final Sınavı", type: "quiz", duration: "20 dk", completed: false },
        ],
      },
    ],
  },
  {
    id: "web-development",
    title: "Modern Web Geliştirme",
    description:
      "HTML, CSS, JavaScript, React ve Node.js ile full-stack web geliştirme.",
    category: "Web Geliştirme",
    level: "Başlangıç",
    icon: "🌐",
    totalModules: 4,
    totalLessons: 20,
    estimatedHours: 16,
    progress: 0,
    enrolled: false,
    tags: ["React", "Node.js", "TypeScript"],
    instructor: "Orka AI",
    rating: 4.7,
    students: 3120,
    modules: [
      {
        id: "web-m1",
        title: "HTML & CSS Temelleri",
        description: "Web'in yapı taşları: HTML semantik yapısı ve CSS styling.",
        duration: "3 saat",
        lessons: [
          { id: "web-l1", title: "HTML Yapısı", type: "article", duration: "20 dk", completed: false },
          { id: "web-l2", title: "CSS Temelleri", type: "article", duration: "25 dk", completed: false },
          { id: "web-l3", title: "Flexbox ve Grid", type: "article", duration: "30 dk", completed: false },
          { id: "web-l4", title: "Responsive Tasarım", type: "exercise", duration: "35 dk", completed: false },
          { id: "web-l5", title: "Modül Sınavı", type: "quiz", duration: "10 dk", completed: false },
        ],
      },
      {
        id: "web-m2",
        title: "JavaScript Temelleri",
        description: "Modern JavaScript: ES6+, async/await, DOM manipülasyonu.",
        duration: "4 saat",
        lessons: [
          { id: "web-l6", title: "Değişkenler ve Fonksiyonlar", type: "article", duration: "20 dk", completed: false },
          { id: "web-l7", title: "Async/Await ve Promises", type: "article", duration: "25 dk", completed: false },
          { id: "web-l8", title: "DOM Manipülasyonu", type: "exercise", duration: "30 dk", completed: false },
          { id: "web-l9", title: "Fetch API", type: "article", duration: "20 dk", completed: false },
          { id: "web-l10", title: "Modül Sınavı", type: "quiz", duration: "15 dk", completed: false },
        ],
      },
      {
        id: "web-m3",
        title: "React ile Frontend",
        description: "Component-based UI, hooks, state management ve routing.",
        duration: "5 saat",
        lessons: [
          { id: "web-l11", title: "React Temelleri", type: "article", duration: "25 dk", completed: false },
          { id: "web-l12", title: "Hooks (useState, useEffect)", type: "article", duration: "30 dk", completed: false },
          { id: "web-l13", title: "React Router", type: "article", duration: "20 dk", completed: false },
          { id: "web-l14", title: "Todo App Projesi", type: "exercise", duration: "45 dk", completed: false },
          { id: "web-l15", title: "Modül Sınavı", type: "quiz", duration: "15 dk", completed: false },
        ],
      },
      {
        id: "web-m4",
        title: "Node.js ile Backend",
        description: "Express, REST API, veritabanı bağlantısı ve deployment.",
        duration: "4 saat",
        lessons: [
          { id: "web-l16", title: "Node.js ve Express", type: "article", duration: "25 dk", completed: false },
          { id: "web-l17", title: "REST API Tasarımı", type: "article", duration: "20 dk", completed: false },
          { id: "web-l18", title: "MongoDB Bağlantısı", type: "exercise", duration: "30 dk", completed: false },
          { id: "web-l19", title: "Full-Stack Proje", type: "exercise", duration: "50 dk", completed: false },
          { id: "web-l20", title: "Final Sınavı", type: "quiz", duration: "20 dk", completed: false },
        ],
      },
    ],
  },
  {
    id: "data-science",
    title: "Veri Bilimi ile Analitik",
    description:
      "Pandas, NumPy, veri görselleştirme ve istatistiksel analiz ile veriden anlam çıkarma.",
    category: "Veri Bilimi",
    level: "Orta",
    icon: "📊",
    totalModules: 4,
    totalLessons: 18,
    estimatedHours: 14,
    progress: 0,
    enrolled: false,
    tags: ["Pandas", "NumPy", "Matplotlib"],
    instructor: "Orka AI",
    rating: 4.6,
    students: 1560,
    modules: [
      {
        id: "ds-m1",
        title: "Veri Bilimine Giriş",
        description: "Veri bilimi nedir, araçlar ve iş akışı.",
        duration: "2 saat",
        lessons: [
          { id: "ds-l1", title: "Veri Bilimi Nedir?", type: "article", duration: "15 dk", completed: false },
          { id: "ds-l2", title: "Jupyter Notebook", type: "article", duration: "20 dk", completed: false },
          { id: "ds-l3", title: "NumPy Temelleri", type: "exercise", duration: "25 dk", completed: false },
          { id: "ds-l4", title: "Modül Sınavı", type: "quiz", duration: "10 dk", completed: false },
        ],
      },
      {
        id: "ds-m2",
        title: "Pandas ile Veri İşleme",
        description: "DataFrame, veri temizleme, birleştirme ve gruplama.",
        duration: "3.5 saat",
        lessons: [
          { id: "ds-l5", title: "DataFrame Temelleri", type: "article", duration: "20 dk", completed: false },
          { id: "ds-l6", title: "Veri Temizleme", type: "article", duration: "25 dk", completed: false },
          { id: "ds-l7", title: "Gruplama ve Birleştirme", type: "article", duration: "25 dk", completed: false },
          { id: "ds-l8", title: "Pratik Proje", type: "exercise", duration: "35 dk", completed: false },
          { id: "ds-l9", title: "Modül Sınavı", type: "quiz", duration: "15 dk", completed: false },
        ],
      },
      {
        id: "ds-m3",
        title: "Veri Görselleştirme",
        description: "Matplotlib, Seaborn ve interaktif grafikler.",
        duration: "3 saat",
        lessons: [
          { id: "ds-l10", title: "Matplotlib Temelleri", type: "article", duration: "20 dk", completed: false },
          { id: "ds-l11", title: "Seaborn ile İleri Grafikler", type: "article", duration: "25 dk", completed: false },
          { id: "ds-l12", title: "Dashboard Projesi", type: "exercise", duration: "40 dk", completed: false },
          { id: "ds-l13", title: "Modül Sınavı", type: "quiz", duration: "15 dk", completed: false },
        ],
      },
      {
        id: "ds-m4",
        title: "İstatistiksel Analiz",
        description: "Hipotez testleri, korelasyon ve regresyon analizi.",
        duration: "3.5 saat",
        lessons: [
          { id: "ds-l14", title: "Temel İstatistik", type: "article", duration: "20 dk", completed: false },
          { id: "ds-l15", title: "Hipotez Testleri", type: "article", duration: "25 dk", completed: false },
          { id: "ds-l16", title: "Korelasyon ve Regresyon", type: "article", duration: "25 dk", completed: false },
          { id: "ds-l17", title: "Analiz Projesi", type: "exercise", duration: "40 dk", completed: false },
          { id: "ds-l18", title: "Final Sınavı", type: "quiz", duration: "20 dk", completed: false },
        ],
      },
    ],
  },
  {
    id: "csharp-advanced",
    title: "C# İleri Seviye",
    description:
      "Generics, LINQ, async programlama, design patterns ve .NET ekosistemi.",
    category: "Programlama",
    level: "İleri",
    icon: "⚡",
    totalModules: 4,
    totalLessons: 20,
    estimatedHours: 18,
    progress: 12,
    enrolled: true,
    tags: ["C#", ".NET", "Design Patterns"],
    instructor: "Orka AI",
    rating: 4.7,
    students: 980,
    modules: [
      {
        id: "cs-m1",
        title: "Generics ve Collections",
        description: "Generic tipler, constraints ve custom collection'lar.",
        duration: "3 saat",
        lessons: [
          { id: "cs-l1", title: "Generic Tipler", type: "article", duration: "20 dk", completed: true },
          { id: "cs-l2", title: "Constraints", type: "article", duration: "20 dk", completed: true },
          { id: "cs-l3", title: "Custom Collections", type: "exercise", duration: "30 dk", completed: false },
          { id: "cs-l4", title: "Covariance ve Contravariance", type: "article", duration: "25 dk", completed: false },
          { id: "cs-l5", title: "Modül Sınavı", type: "quiz", duration: "15 dk", completed: false },
        ],
      },
      {
        id: "cs-m2",
        title: "LINQ ve Functional C#",
        description: "LINQ sorgulama, lambda ifadeleri ve fonksiyonel programlama.",
        duration: "3.5 saat",
        lessons: [
          { id: "cs-l6", title: "LINQ Temelleri", type: "article", duration: "20 dk", completed: false },
          { id: "cs-l7", title: "Lambda ve Delegates", type: "article", duration: "25 dk", completed: false },
          { id: "cs-l8", title: "LINQ to Objects", type: "exercise", duration: "30 dk", completed: false },
          { id: "cs-l9", title: "Expression Trees", type: "article", duration: "25 dk", completed: false },
          { id: "cs-l10", title: "Modül Sınavı", type: "quiz", duration: "15 dk", completed: false },
        ],
      },
      {
        id: "cs-m3",
        title: "Async Programlama",
        description: "async/await, Task, paralel programlama ve concurrency.",
        duration: "4 saat",
        lessons: [
          { id: "cs-l11", title: "async/await Temelleri", type: "article", duration: "25 dk", completed: false },
          { id: "cs-l12", title: "Task ve Task<T>", type: "article", duration: "25 dk", completed: false },
          { id: "cs-l13", title: "Parallel.ForEach", type: "article", duration: "20 dk", completed: false },
          { id: "cs-l14", title: "Concurrency Patterns", type: "exercise", duration: "35 dk", completed: false },
          { id: "cs-l15", title: "Modül Sınavı", type: "quiz", duration: "15 dk", completed: false },
        ],
      },
      {
        id: "cs-m4",
        title: "Design Patterns",
        description: "Creational, structural ve behavioral pattern'lar.",
        duration: "5 saat",
        lessons: [
          { id: "cs-l16", title: "Singleton ve Factory", type: "article", duration: "25 dk", completed: false },
          { id: "cs-l17", title: "Observer ve Strategy", type: "article", duration: "25 dk", completed: false },
          { id: "cs-l18", title: "Repository Pattern", type: "article", duration: "20 dk", completed: false },
          { id: "cs-l19", title: "Pattern Projesi", type: "exercise", duration: "45 dk", completed: false },
          { id: "cs-l20", title: "Final Sınavı", type: "quiz", duration: "20 dk", completed: false },
        ],
      },
    ],
  },
  {
    id: "sql-databases",
    title: "SQL ve Veritabanı Yönetimi",
    description:
      "İlişkisel veritabanları, SQL sorguları, normalizasyon ve performans optimizasyonu.",
    category: "Veritabanı",
    level: "Başlangıç",
    icon: "🗄️",
    totalModules: 4,
    totalLessons: 16,
    estimatedHours: 10,
    progress: 0,
    enrolled: false,
    tags: ["SQL", "PostgreSQL", "Normalizasyon"],
    instructor: "Orka AI",
    rating: 4.5,
    students: 1240,
    modules: [
      {
        id: "sql-m1",
        title: "SQL Temelleri",
        description: "SELECT, INSERT, UPDATE, DELETE ve temel sorgular.",
        duration: "2 saat",
        lessons: [
          { id: "sql-l1", title: "Veritabanı Nedir?", type: "article", duration: "15 dk", completed: false },
          { id: "sql-l2", title: "SELECT Sorguları", type: "article", duration: "20 dk", completed: false },
          { id: "sql-l3", title: "CRUD İşlemleri", type: "exercise", duration: "25 dk", completed: false },
          { id: "sql-l4", title: "Modül Sınavı", type: "quiz", duration: "10 dk", completed: false },
        ],
      },
      {
        id: "sql-m2",
        title: "İleri SQL",
        description: "JOIN'ler, alt sorgular, aggregate fonksiyonlar.",
        duration: "2.5 saat",
        lessons: [
          { id: "sql-l5", title: "JOIN Türleri", type: "article", duration: "25 dk", completed: false },
          { id: "sql-l6", title: "Alt Sorgular", type: "article", duration: "20 dk", completed: false },
          { id: "sql-l7", title: "GROUP BY ve HAVING", type: "exercise", duration: "25 dk", completed: false },
          { id: "sql-l8", title: "Modül Sınavı", type: "quiz", duration: "15 dk", completed: false },
        ],
      },
      {
        id: "sql-m3",
        title: "Veritabanı Tasarımı",
        description: "Normalizasyon, ER diyagramları ve şema tasarımı.",
        duration: "2.5 saat",
        lessons: [
          { id: "sql-l9", title: "Normalizasyon (1NF-3NF)", type: "article", duration: "25 dk", completed: false },
          { id: "sql-l10", title: "ER Diyagramları", type: "article", duration: "20 dk", completed: false },
          { id: "sql-l11", title: "Şema Tasarım Projesi", type: "exercise", duration: "35 dk", completed: false },
          { id: "sql-l12", title: "Modül Sınavı", type: "quiz", duration: "15 dk", completed: false },
        ],
      },
      {
        id: "sql-m4",
        title: "Performans ve Güvenlik",
        description: "İndeksler, sorgu optimizasyonu ve güvenlik.",
        duration: "3 saat",
        lessons: [
          { id: "sql-l13", title: "İndeksler", type: "article", duration: "20 dk", completed: false },
          { id: "sql-l14", title: "Sorgu Optimizasyonu", type: "article", duration: "25 dk", completed: false },
          { id: "sql-l15", title: "SQL Injection Koruması", type: "article", duration: "20 dk", completed: false },
          { id: "sql-l16", title: "Final Sınavı", type: "quiz", duration: "20 dk", completed: false },
        ],
      },
    ],
  },
];
